# Generated by Django 5.2.7 on 2025-10-15 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchiveYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True, verbose_name="Год")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Архивный год",
                "verbose_name_plural": "Архивные годы",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Сообщение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EditorialBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "position",
                    models.CharField(max_length=200, verbose_name="Должность"),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Учреждение"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="editorial_board/", verbose_name="Фото"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Член редакционной коллегии",
                "verbose_name_plural": "Редакционная коллегия",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="JournalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название журнала"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "issn_print",
                    models.CharField(
                        max_length=20, verbose_name="ISSN (печатная версия)"
                    ),
                ),
                (
                    "issn_online",
                    models.CharField(
                        max_length=20, verbose_name="ISSN (онлайн версия)"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(max_length=200, verbose_name="Издатель"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="journal/", verbose_name="Логотип"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        upload_to="journal/",
                        verbose_name="Главное изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о журнале",
                "verbose_name_plural": "Информация о журнале",
            },
        ),
        migrations.CreateModel(
            name="JournalIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Год")),
                ("number", models.IntegerField(verbose_name="Номер")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="covers/", verbose_name="Обложка"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Текущий выпуск"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Выпуск журнала",
                "verbose_name_plural": "Выпуски журнала",
                "ordering": ["-year", "-number"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Название")),
                ("abstract", models.TextField(verbose_name="Аннотация")),
                ("authors", models.TextField(verbose_name="Авторы")),
                (
                    "keywords",
                    models.TextField(blank=True, verbose_name="Ключевые слова"),
                ),
                (
                    "doi",
                    models.CharField(blank=True, max_length=100, verbose_name="DOI"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, upload_to="articles/", verbose_name="PDF файл"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="journal.journalissue",
                        verbose_name="Выпуск",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-created_at"],
            },
        ),
    ]
