# Generated by Django 5.2.7 on 2025-10-16 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archiveyear",
            options={
                "ordering": ["-end_year"],
                "verbose_name": "Архивный промежуток лет",
                "verbose_name_plural": "Архивные промежутки лет",
            },
        ),
        migrations.RemoveField(
            model_name="archiveyear",
            name="year",
        ),
        migrations.AddField(
            model_name="archiveyear",
            name="end_year",
            field=models.IntegerField(default=1959, verbose_name="Год окончания"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="archiveyear",
            name="slug",
            field=models.SlugField(
                default=1, unique=True, verbose_name="Slug (например, 1957-1959)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="archiveyear",
            name="start_year",
            field=models.IntegerField(default=1957, verbose_name="Год начала"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journalissue",
            name="archive_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="journal.archiveyear",
                verbose_name="Архивный промежуток",
            ),
        ),
    ]
