# Generated by Django 5.2 on 2025-12-08 12:27

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_archiveyear_options_remove_archiveyear_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveyear',
            options={'verbose_name': 'Архивный период', 'verbose_name_plural': 'Архивные периоды'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['page_start'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения с сайта'},
        ),
        migrations.AlterModelOptions(
            name='editorialboard',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Член редсовета', 'verbose_name_plural': 'Редакционная коллегия'},
        ),
        migrations.AlterModelOptions(
            name='journalissue',
            options={'ordering': ['-year', '-number'], 'verbose_name': 'Выпуск', 'verbose_name_plural': 'Выпуски'},
        ),
        migrations.RemoveField(
            model_name='archiveyear',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='editorialboard',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='journalinfo',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='journalinfo',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='journalissue',
            name='archive_year',
        ),
        migrations.RemoveField(
            model_name='journalissue',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='journalissue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='journalissue',
            name='title',
        ),
        migrations.RemoveField(
            model_name='journalissue',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='article',
            name='page_end',
            field=models.IntegerField(default=0, verbose_name='Стр. конец'),
        ),
        migrations.AddField(
            model_name='article',
            name='page_start',
            field=models.IntegerField(default=0, verbose_name='Стр. начало'),
        ),
        migrations.AddField(
            model_name='article',
            name='rubric',
            field=models.CharField(blank=True, max_length=200, verbose_name='Рубрика'),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.issue_cover_path, verbose_name='Обложка (картинка)'),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='full_pdf',
            field=models.FileField(blank=True, null=True, upload_to=journal.models.issue_pdf_path, verbose_name='Полный PDF выпуска'),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='volume',
            field=models.CharField(blank=True, max_length=50, verbose_name='Том (например, 67)'),
        ),
        migrations.AlterField(
            model_name='archiveyear',
            name='end_year',
            field=models.IntegerField(verbose_name='Год конца'),
        ),
        migrations.AlterField(
            model_name='archiveyear',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL slug (например, 2020-2025)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(max_length=500, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=journal.models.article_pdf_path, verbose_name='PDF файл статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='editorialboard',
            name='institution',
            field=models.CharField(blank=True, max_length=300, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='editorialboard',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='editorialboard',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='editorialboard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='editorial/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='editorialboard',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность/Статус'),
        ),
        migrations.AlterField(
            model_name='journalinfo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание журнала'),
        ),
        migrations.AlterField(
            model_name='journalinfo',
            name='issn_online',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISSN (Online)'),
        ),
        migrations.AlterField(
            model_name='journalinfo',
            name='issn_print',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISSN (Print)'),
        ),
        migrations.AlterField(
            model_name='journalinfo',
            name='publisher',
            field=models.CharField(default='МИИГАиК', max_length=200, verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='journalinfo',
            name='title',
            field=models.CharField(default='Известия вузов. Геодезия и аэрофотосъемка', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Текущий выпуск (на главной)'),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Номер выпуска'),
        ),
        migrations.AlterField(
            model_name='journalissue',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Год издания'),
        ),
    ]
